spring:
  application:
    name: redirect_service
  kafka:
    bootstrap-server: localhost:9092

server:
  port: 8083

app:
  link-service:
    base-url: http://localhost:8082
  analytic-service:
    base-url: http://localhost:8084