spring:
  application:
    name: redirect_service
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}

server:
  port: 8083

app:
  link-service:
    base-url: http://${LINK_HOST:localhost}:${LINK_PORT:8082}
  analytics-service:
    base-url: http://${ANALYTICS_HOST:localhost}:${ANALYTICS_PORT:8084}