spring:
  application:
    name: analytics_service
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: analytics-service-group
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:analyticdb}
    username: ${DB_USER:analyticuser}
    password: ${DB_PASSWORD:analyticpass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084
